import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { getApiBaseUrl } from '../apiBase';

const API = getApiBaseUrl();

export default function AdminPanel() {
  const [tab, setTab] = useState('tenants');
  const [adminToken, setAdminToken] = useState(() => localStorage.getItem('oh_admin_token') || '');
  const [loginForm, setLoginForm] = useState({ email: '', password: '' });
  const [loginErr, setLoginErr] = useState('');
  const [loggedIn, setLoggedIn] = useState(false);

  // Data
  const [tenants, setTenants] = useState([]);
  const [plans, setPlans] = useState([]);
  const [settings, setSettings] = useState({});
  const [stats, setStats] = useState(null);
  const [announcements, setAnnouncements] = useState([]);
  const [newAnnouncement, setNewAnnouncement] = useState({ title: '', message: '', type: 'info', target_plans: '', target_products: '', requires_action: false, action_type: '' });
  const [emailForm, setEmailForm] = useState({ subject: '', body: '', targetPlan: '' });
  const [emailMsg, setEmailMsg] = useState('');
  const [editingTenant, setEditingTenant] = useState(null);
  const [tenantUsers, setTenantUsers] = useState([]);
  const [expandedTenant, setExpandedTenant] = useState(null);
  const [tenantBilling, setTenantBilling] = useState(null);
  const [billingLoading, setBillingLoading] = useState(false);

  const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${adminToken}` };

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoginErr('');
    try {
      const r = await fetch(`${API}/admin/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(loginForm) });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error);
      setAdminToken(data.token);
      localStorage.setItem('oh_admin_token', data.token);
      setLoggedIn(true);
    } catch (err) { setLoginErr(err.message); }
  };

  const fetchData = async () => {
    try {
      const [t, p, s, st, ann] = await Promise.all([
        fetch(`${API}/admin/tenants`, { headers }).then(r => r.json()),
        fetch(`${API}/admin/plans`, { headers }).then(r => r.json()),
        fetch(`${API}/admin/settings`, { headers }).then(r => r.json()),
        fetch(`${API}/admin/stats`, { headers }).then(r => r.json()),
        fetch(`${API}/admin/announcements`, { headers }).then(r => r.json()),
      ]);
      setTenants(t);
      setPlans(Array.isArray(p) ? p : []);
      setSettings(s || {});
      setStats(st);
      setAnnouncements(Array.isArray(ann) ? ann : []);
      setLoggedIn(true);
    } catch {
      setLoggedIn(false);
    }
  };

  useEffect(() => {
    if (adminToken) fetchData();
  }, [adminToken]);

  const handlePlanUpdate = async (key, field, value) => {
    setPlans(plans.map(p => p.key === key ? { ...p, [field]: value } : p));
  };

  const savePlans = async () => {
    const r = await fetch(`${API}/admin/plans`, { method: 'PUT', headers, body: JSON.stringify(plans) });
    const d = await r.json();
    if (!r.ok) return alert(d.error || 'Błąd zapisu planów');
    fetchData();
    alert(`Plany zapisane! Auto-wygenerowane ceny Stripe: ${d.autoGenerated || 0}`);
  };

  const saveSettings = async () => {
    await fetch(`${API}/admin/settings`, { method: 'PUT', headers, body: JSON.stringify(settings) });
    alert('Ustawienia zapisane!');
  };

  const handleSettingChange = (key, value) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };

  const handleDeleteTenant = async (id) => {
    if (!confirm('Usunąć tego tenanta i wszystkie jego dane?')) return;
    await fetch(`${API}/admin/tenants/${id}`, { method: 'DELETE', headers });
    setTenants(tenants.filter(t => t.id !== id));
  };

  const handlePurgeTenant = async (id) => {
    if (!confirm('To trwale usunie firmę i jej dane (OneHost + dane zewnętrzne). Kontynuować?')) return;
    try {
      const r = await fetch(`${API}/admin/tenants/${id}/purge`, { method: 'DELETE', headers });
      const d = await r.json();
      if (!r.ok) return alert(d.error || 'Nie udało się usunąć danych');
      setTenants(tenants.filter(t => t.id !== id));
      alert('Dane firmy zostały usunięte.');
    } catch (err) {
      alert('Błąd: ' + err.message);
    }
  };

  const handleEditTenant = (t) => {
    setEditingTenant({ ...t });
    setTenantBilling(null);
    loadTenantBilling(t.id);
  };

  const loadTenantBilling = async (tenantId) => {
    setBillingLoading(true);
    try {
      const r = await fetch(`${API}/admin/tenants/${tenantId}/billing`, { headers });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error || 'Błąd pobierania billing');
      setTenantBilling(d);
    } catch (err) {
      setTenantBilling({ error: err.message });
    } finally {
      setBillingLoading(false);
    }
  };

  const cancelTenantSubscription = async () => {
    if (!editingTenant) return;
    if (!confirm('Anulować subskrypcję tej firmy na koniec okresu?')) return;
    try {
      const r = await fetch(`${API}/admin/tenants/${editingTenant.id}/billing/cancel`, { method: 'POST', headers });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error || 'Błąd anulowania subskrypcji');
      alert('Subskrypcja ustawiona do anulowania na koniec okresu.');
      setEditingTenant(p => ({ ...p, subscription_status: 'cancel_pending' }));
      setTenants(tenants.map(t => t.id === editingTenant.id ? { ...t, subscription_status: 'cancel_pending' } : t));
      loadTenantBilling(editingTenant.id);
    } catch (err) {
      alert('Błąd: ' + err.message);
    }
  };

  const detachTenantCards = async () => {
    if (!editingTenant) return;
    if (!confirm('Odpiąć wszystkie karty tej firmy w Stripe?')) return;
    try {
      const r = await fetch(`${API}/admin/tenants/${editingTenant.id}/billing/detach-cards`, { method: 'POST', headers });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error || 'Błąd odpinania kart');
      alert(`Odpięto karty: ${d.detached || 0}`);
      loadTenantBilling(editingTenant.id);
    } catch (err) {
      alert('Błąd: ' + err.message);
    }
  };

  const saveTenant = async () => {
    if (!editingTenant) return;
    try {
      const r = await fetch(`${API}/admin/tenants/${editingTenant.id}`, {
        method: 'PUT', headers, body: JSON.stringify({
          plan: editingTenant.plan,
          subscription_status: editingTenant.subscription_status,
          trial_ends_at: editingTenant.trial_ends_at,
          products: editingTenant.products,
          max_profiles: editingTenant.max_profiles,
          company_name: editingTenant.company_name,
          allow_without_card: !!editingTenant.allow_without_card,
        })
      });
      if (!r.ok) { const d = await r.json(); alert(d.error || 'Błąd'); return; }
      setTenants(tenants.map(t => t.id === editingTenant.id ? { ...t, ...editingTenant } : t));
      setEditingTenant(null);
    } catch (e) { alert('Błąd: ' + e.message); }
  };

  const loadTenantUsers = async (tenantId) => {
    if (expandedTenant === tenantId) { setExpandedTenant(null); setTenantUsers([]); return; }
    try {
      const r = await fetch(`${API}/admin/tenants/${tenantId}/users`, { headers });
      const data = await r.json();
      setTenantUsers(Array.isArray(data) ? data : []);
      setExpandedTenant(tenantId);
    } catch { setTenantUsers([]); }
  };

  if (!loggedIn) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4">
        <div className="w-full max-w-sm">
          <div className="text-center mb-8">
            <div className="w-12 h-12 bg-gradient-to-br from-teal-500 to-cyan-600 rounded-xl flex items-center justify-center text-white font-bold text-lg mx-auto mb-4">OH</div>
            <h1 className="text-xl font-bold text-white">Admin Panel</h1>
          </div>
          <form onSubmit={handleLogin} className="bg-slate-800 rounded-2xl p-6 space-y-4">
            {loginErr && <div className="text-red-400 text-sm">{loginErr}</div>}
            <input type="email" value={loginForm.email} onChange={e => setLoginForm(p => ({ ...p, email: e.target.value }))} placeholder="Email" className="w-full bg-slate-700 border border-slate-600 rounded-lg px-4 py-2.5 text-sm text-white placeholder-slate-400 outline-none focus:ring-2 focus:ring-primary" required />
            <input type="password" value={loginForm.password} onChange={e => setLoginForm(p => ({ ...p, password: e.target.value }))} placeholder="Hasło" className="w-full bg-slate-700 border border-slate-600 rounded-lg px-4 py-2.5 text-sm text-white placeholder-slate-400 outline-none focus:ring-2 focus:ring-primary" required />
            <button type="submit" className="w-full bg-primary text-white py-2.5 rounded-lg text-sm font-semibold hover:bg-primary-dark cursor-pointer">Zaloguj</button>
          </form>
        </div>
      </div>
    );
  }

  const tabs = [
    { id: 'tenants', label: 'Firmy', icon: '🏢' },
    { id: 'plans', label: 'Plany', icon: '💳' },
    { id: 'announcements', label: 'Komunikaty', icon: '📢' },
    { id: 'email', label: 'Email', icon: '✉️' },
    { id: 'settings', label: 'Ustawienia', icon: '⚙️' },
    { id: 'stats', label: 'Statystyki', icon: '📊' },
  ];

  return (
    <div className="min-h-screen bg-slate-900 text-white">
      {/* Header */}
      <header className="bg-slate-800 border-b border-slate-700">
        <div className="max-w-7xl mx-auto px-4 flex items-center justify-between h-14">
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 bg-gradient-to-br from-teal-500 to-cyan-600 rounded-lg flex items-center justify-center text-white font-bold text-xs">OH</div>
            <span className="font-bold">Admin Panel</span>
          </div>
          <div className="flex items-center gap-4">
            <Link to="/" className="text-sm text-slate-400 hover:text-white">Strona główna</Link>
            <button
              onClick={() => { setAdminToken(''); setLoggedIn(false); localStorage.removeItem('oh_admin_token'); }}
              className="text-sm text-red-400 hover:text-red-300 cursor-pointer"
            >Wyloguj</button>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 py-6">
        {/* Tabs */}
        <div className="flex gap-1 mb-6 bg-slate-800 rounded-xl p-1 w-fit">
          {tabs.map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-all cursor-pointer ${tab === t.id ? 'bg-slate-700 text-white' : 'text-slate-400 hover:text-white'}`}
            >
              {t.icon} {t.label}
            </button>
          ))}
        </div>

        {/* Tenant management */}
        {tab === 'tenants' && (
          <div>
            <h2 className="text-xl font-bold mb-4">Firmy ({tenants.length})</h2>

            {/* Edit modal */}
            {editingTenant && (
              <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
                <div className="bg-slate-800 rounded-2xl border border-slate-700 p-6 w-full max-w-lg mx-4 space-y-4">
                  <h3 className="text-lg font-bold">Edytuj firmę #{editingTenant.id}</h3>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="col-span-2">
                      <label className="text-xs text-slate-400 block mb-1">Nazwa firmy</label>
                      <input value={editingTenant.company_name || ''} onChange={e => setEditingTenant(p => ({...p, company_name: e.target.value}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1">Plan</label>
                      <select value={editingTenant.plan || 'trial'} onChange={e => setEditingTenant(p => ({...p, plan: e.target.value}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                        <option value="trial">Trial</option>
                        {plans.map(p => <option key={p.key} value={p.key}>{p.name}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1">Status subskrypcji</label>
                      <select value={editingTenant.subscription_status || 'trialing'} onChange={e => setEditingTenant(p => ({...p, subscription_status: e.target.value}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                        <option value="trialing">Trialing</option>
                        <option value="active">Active</option>
                        <option value="canceled">Canceled</option>
                        <option value="past_due">Past Due</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1">Trial / dostęp do</label>
                      <input type="date" value={(editingTenant.trial_ends_at || '').slice(0,10)} onChange={e => setEditingTenant(p => ({...p, trial_ends_at: e.target.value}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 block mb-1">Max profili</label>
                      <input type="number" min={1} max={50} value={editingTenant.max_profiles || 1} onChange={e => setEditingTenant(p => ({...p, max_profiles: parseInt(e.target.value) || 1}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none" />
                    </div>
                    <div className="col-span-2">
                      <label className="text-xs text-slate-400 block mb-1">Produkty (przecinek)</label>
                      <input value={editingTenant.products || ''} onChange={e => setEditingTenant(p => ({...p, products: e.target.value}))}
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none"
                        placeholder="shiftplanner,equipment,certtrack" />
                    </div>
                    <div className="col-span-2">
                      <label className="flex items-center gap-2 text-sm text-slate-300">
                        <input
                          type="checkbox"
                          checked={!!editingTenant.allow_without_card}
                          onChange={e => setEditingTenant(p => ({ ...p, allow_without_card: e.target.checked ? 1 : 0 }))}
                          className="accent-teal-500"
                        />
                        Zezwól na trial bez dodanej metody płatniczej dla tej firmy
                      </label>
                    </div>
                  </div>
                  <div className="bg-slate-900/40 border border-slate-700 rounded-xl p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-semibold text-slate-300">Billing (Stripe)</h4>
                      <button onClick={() => editingTenant && loadTenantBilling(editingTenant.id)} className="text-xs text-slate-400 hover:text-white cursor-pointer">Odśwież</button>
                    </div>

                    {billingLoading && <div className="text-xs text-slate-400">Ładowanie danych billingowych...</div>}
                    {!billingLoading && tenantBilling?.error && <div className="text-xs text-red-400">{tenantBilling.error}</div>}
                    {!billingLoading && tenantBilling && !tenantBilling.error && (
                      <div className="space-y-2 text-xs text-slate-300">
                        <div>Status: <span className="text-white">{tenantBilling.subscriptionStatus || '—'}</span></div>
                        <div>Customer ID: <span className="text-slate-400">{tenantBilling.customerId || '—'}</span></div>
                        <div>Subscription ID: <span className="text-slate-400">{tenantBilling.subscriptionId || '—'}</span></div>
                        <div>Karty: <span className="text-white">{tenantBilling.paymentMethods?.length || 0}</span></div>
                        {(tenantBilling.paymentMethods || []).length > 0 && (
                          <div className="text-slate-400">
                            {(tenantBilling.paymentMethods || []).map(pm => (
                              <div key={pm.id}>• {pm.brand} •••• {pm.last4} ({pm.exp_month}/{pm.exp_year})</div>
                            ))}
                          </div>
                        )}
                      </div>
                    )}

                    <div className="flex gap-2 flex-wrap">
                      <button onClick={cancelTenantSubscription} className="px-3 py-1 bg-yellow-600/30 text-yellow-300 rounded-lg text-xs hover:bg-yellow-600/50 cursor-pointer">Anuluj subskrypcję</button>
                      <button onClick={detachTenantCards} className="px-3 py-1 bg-red-600/30 text-red-300 rounded-lg text-xs hover:bg-red-600/50 cursor-pointer">Odepnij wszystkie karty</button>
                    </div>
                  </div>
                  {/* Quick plan presets */}
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">Szybkie ustawienia</label>
                    <div className="flex gap-2 flex-wrap">
                      <button onClick={() => setEditingTenant(p => ({...p, plan: 'trial', subscription_status: 'trialing', trial_ends_at: new Date(Date.now()+7*86400000).toISOString().slice(0,10)}))}
                        className="px-3 py-1 bg-teal-600/30 text-teal-400 rounded-lg text-xs hover:bg-teal-600/50 cursor-pointer">Trial 7 dni</button>
                      <button onClick={() => setEditingTenant(p => ({...p, plan: 'trial', subscription_status: 'trialing', trial_ends_at: new Date(Date.now()+30*86400000).toISOString().slice(0,10)}))}
                        className="px-3 py-1 bg-teal-600/30 text-teal-400 rounded-lg text-xs hover:bg-teal-600/50 cursor-pointer">Trial 30 dni</button>
                      {plans.map(pl => (
                        <button key={pl.key} onClick={() => setEditingTenant(p => ({...p, plan: pl.key, subscription_status: 'active', max_profiles: pl.max_profiles || 1, trial_ends_at: new Date(Date.now()+365*86400000).toISOString().slice(0,10)}))}
                          className="px-3 py-1 bg-green-600/30 text-green-400 rounded-lg text-xs hover:bg-green-600/50 cursor-pointer">{pl.name} (1 rok)</button>
                      ))}
                      <button onClick={() => setEditingTenant(p => ({...p, subscription_status: 'canceled'}))}
                        className="px-3 py-1 bg-red-600/30 text-red-400 rounded-lg text-xs hover:bg-red-600/50 cursor-pointer">Anuluj subskrypcję</button>
                    </div>
                  </div>
                  <div className="flex gap-3 justify-end pt-2">
                    <button onClick={() => setEditingTenant(null)} className="px-4 py-2 text-sm text-slate-400 hover:text-white cursor-pointer">Anuluj</button>
                    <button onClick={saveTenant} className="px-5 py-2 bg-primary text-white rounded-lg text-sm font-semibold hover:bg-primary-dark cursor-pointer">Zapisz</button>
                  </div>
                </div>
              </div>
            )}

            <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-700 bg-slate-800/50">
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">ID</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Firma</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Email</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Plan</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Status</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Trial do</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Produkty</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Utworzono</th>
                    <th className="text-left px-4 py-3 text-slate-400 font-medium">Akcje</th>
                  </tr>
                </thead>
                <tbody>
                  {tenants.map(t => (
                    <React.Fragment key={t.id}>
                      <tr className="border-b border-slate-700/50 hover:bg-slate-700/30">
                        <td className="px-4 py-3 text-slate-400">{t.id}</td>
                        <td className="px-4 py-3 font-medium">{t.company_name}</td>
                        <td className="px-4 py-3 text-slate-300 text-xs">{t.owner_email || '—'}</td>
                        <td className="px-4 py-3"><span className="px-2 py-0.5 bg-slate-700 rounded text-xs">{t.plan}</span></td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                            t.subscription_status === 'active' ? 'bg-green-500/20 text-green-400' :
                            t.subscription_status === 'trialing' ? 'bg-teal-500/20 text-teal-400' :
                            'bg-red-500/20 text-red-400'
                          }`}>{t.subscription_status}</span>
                        </td>
                        <td className="px-4 py-3 text-slate-400">{(t.trial_ends_at || '').slice(0,10)}</td>
                        <td className="px-4 py-3 text-slate-400 text-xs">{t.products}</td>
                        <td className="px-4 py-3 text-slate-400">{t.created_at?.split('T')[0]}</td>
                        <td className="px-4 py-3 flex items-center gap-2">
                          <button onClick={() => handleEditTenant(t)} className="text-teal-400 hover:text-teal-300 text-xs cursor-pointer">Edytuj</button>
                          <button onClick={() => loadTenantUsers(t.id)} className="text-slate-400 hover:text-white text-xs cursor-pointer">
                            {expandedTenant === t.id ? 'Ukryj' : 'Użytkownicy'}
                          </button>
                          <button onClick={() => handleDeleteTenant(t.id)} className="text-red-400 hover:text-red-300 text-xs cursor-pointer">Usuń</button>
                          <button onClick={() => handlePurgeTenant(t.id)} className="text-orange-400 hover:text-orange-300 text-xs cursor-pointer">Usuń dane</button>
                        </td>
                      </tr>
                      {expandedTenant === t.id && (
                        <tr className="bg-slate-700/20">
                          <td colSpan={9} className="px-4 py-3">
                            <div className="text-xs text-slate-400 mb-2 font-medium">Użytkownicy firmy: {t.company_name}</div>
                            {tenantUsers.length === 0 ? (
                              <div className="text-xs text-slate-500 italic">Brak użytkowników</div>
                            ) : (
                              <div className="grid gap-2">
                                {tenantUsers.map(u => (
                                  <div key={u.id} className="flex items-center gap-3 bg-slate-800/60 rounded-lg px-3 py-2 text-xs">
                                    <span className="text-slate-300 font-medium min-w-[140px]">{u.email}</span>
                                    <span className="text-slate-400">{u.name || '—'}</span>
                                    <span className={`px-2 py-0.5 rounded font-medium ${
                                      u.role === 'admin' ? 'bg-purple-500/20 text-purple-400' :
                                      u.role === 'manager' ? 'bg-blue-500/20 text-blue-400' :
                                      'bg-slate-600/60 text-slate-400'
                                    }`}>{u.role}</span>
                                    <span className={`ml-auto ${u.email_verified ? 'text-green-400' : 'text-yellow-400'}`}>
                                      {u.email_verified ? '✓ Zweryfikowany' : '⏳ Niezweryfikowany'}
                                    </span>
                                    <span className="text-slate-500">{u.created_at?.split('T')[0]}</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Plans management */}
        {tab === 'plans' && (
          <div>
            <h2 className="text-xl font-bold mb-4">Konfiguracja planów</h2>
            <div className="space-y-4">
              {plans.map((plan, idx) => (
                <div key={plan.key} className="bg-slate-800 rounded-xl border border-slate-700 p-5">
                  <div className="flex items-center gap-4 mb-4">
                    <span className="text-lg font-bold">{plan.name}</span>
                    <span className="text-xs text-slate-500 bg-slate-700 px-2 py-0.5 rounded">{plan.key}</span>
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Cena PLN/mies.</label>
                      <input type="number" value={plan.price_pln} onChange={e => handlePlanUpdate(plan.key, 'price_pln', Number(e.target.value))} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                    </div>
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Cena PLN/rok</label>
                      <input type="number" value={plan.price_pln_yearly} onChange={e => handlePlanUpdate(plan.key, 'price_pln_yearly', Number(e.target.value))} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                    </div>
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Limit rekordów / aplikację</label>
                      <input type="number" value={plan.max_employees} onChange={e => handlePlanUpdate(plan.key, 'max_employees', Number(e.target.value))} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                    </div>
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Limit przypisań/profil (0 = bez limitu)</label>
                      <input type="number" value={plan.max_users} onChange={e => handlePlanUpdate(plan.key, 'max_users', Number(e.target.value))} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                    </div>
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Stripe Price ID (mies.)</label>
                      <input type="text" value={plan.stripe_price_id || ''} onChange={e => handlePlanUpdate(plan.key, 'stripe_price_id', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="price_..." />
                    </div>
                    <div>
                      <label className="block text-xs text-slate-400 mb-1">Stripe Price ID (rok.)</label>
                      <input type="text" value={plan.stripe_price_id_yearly || ''} onChange={e => handlePlanUpdate(plan.key, 'stripe_price_id_yearly', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="price_..." />
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <button onClick={savePlans} className="mt-4 bg-primary text-white px-6 py-2.5 rounded-lg text-sm font-medium hover:bg-primary-dark cursor-pointer">Zapisz plany</button>
          </div>
        )}

        {/* Settings */}
        {tab === 'settings' && (
          <div>
            <h2 className="text-xl font-bold mb-4">Ustawienia platformy</h2>
            <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 space-y-5">
              <div>
                <h3 className="text-sm font-semibold text-slate-300 mb-3">Stripe</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">Stripe Secret Key</label>
                    <input type="password" value={settings.stripe_secret_key || ''} onChange={e => handleSettingChange('stripe_secret_key', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="sk_..." />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">Metody płatności (card,blik,p24)</label>
                    <input type="text" value={settings.stripe_payment_methods || 'card'} onChange={e => handleSettingChange('stripe_payment_methods', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">Zniżka pakietowa (%)</label>
                    <input type="number" value={settings.bundle_discount || 20} onChange={e => handleSettingChange('bundle_discount', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                  </div>
                </div>
              </div>
              <div>
                <h3 className="text-sm font-semibold text-slate-300 mb-3">SMTP (Email)</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">SMTP Host</label>
                    <input type="text" value={settings.smtp_host || ''} onChange={e => handleSettingChange('smtp_host', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="smtp.gmail.com / mail.onehost.site" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">SMTP Port</label>
                    <input type="number" value={settings.smtp_port || 587} onChange={e => handleSettingChange('smtp_port', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">SMTP Secure (SSL/TLS)</label>
                    <select value={settings.smtp_secure || ''} onChange={e => handleSettingChange('smtp_secure', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                      <option value="">Auto (port 465 = secure)</option>
                      <option value="true">Włączone</option>
                      <option value="false">Wyłączone</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">SMTP User (login)</label>
                    <input type="text" value={settings.smtp_user || ''} onChange={e => handleSettingChange('smtp_user', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="admin@onehost.site" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">SMTP Password</label>
                    <input type="password" value={settings.smtp_pass || ''} onChange={e => handleSettingChange('smtp_pass', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                  </div>
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">Adres nadawcy (From)</label>
                    <input type="text" value={settings.smtp_from || ''} onChange={e => handleSettingChange('smtp_from', e.target.value)} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" placeholder="OneHost <admin@onehost.site>" />
                    <p className="text-xs text-slate-500 mt-1">Np. "OneHost &lt;admin@onehost.site&gt;" — z tego adresu wyślą się maile weryfikacyjne, powiadomienia i masowe wiadomości.</p>
                  </div>
                  <div className="flex items-end">
                    <button
                      type="button"
                      onClick={async () => {
                        try {
                          const r = await fetch(`${API}/admin/test-email`, { method: 'POST', headers });
                          const d = await r.json();
                          alert(d.ok ? `✅ Email testowy wysłany na adres nadawcy (${settings.smtp_from || settings.smtp_user || '?'})` : `❌ Błąd: ${d.error}`);
                        } catch (err) { alert('Błąd: ' + err.message); }
                      }}
                      className="bg-teal-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-teal-700 cursor-pointer w-full"
                    >
                      📧 Wyślij testowy email
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <button onClick={saveSettings} className="mt-4 bg-primary text-white px-6 py-2.5 rounded-lg text-sm font-medium hover:bg-primary-dark cursor-pointer">Zapisz ustawienia</button>
          </div>
        )}

        {/* Announcements management */}
        {tab === 'announcements' && (
          <div>
            <h2 className="text-xl font-bold mb-4">Komunikaty</h2>
            <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 mb-6 space-y-4">
              <h3 className="text-sm font-semibold text-slate-300">Nowy komunikat</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input type="text" value={newAnnouncement.title} onChange={e => setNewAnnouncement(p => ({ ...p, title: e.target.value }))} placeholder="Tytuł" className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                <select value={newAnnouncement.type} onChange={e => setNewAnnouncement(p => ({ ...p, type: e.target.value }))} className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                  <option value="info">Info (niebieski)</option>
                  <option value="warning">Ostrzeżenie (żółty)</option>
                  <option value="danger">Ważne (czerwony)</option>
                  <option value="success">Sukces (zielony)</option>
                </select>
              </div>
              <textarea value={newAnnouncement.message} onChange={e => setNewAnnouncement(p => ({ ...p, message: e.target.value }))} placeholder="Treść komunikatu" rows={3} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <input type="text" value={newAnnouncement.target_plans} onChange={e => setNewAnnouncement(p => ({ ...p, target_plans: e.target.value }))} placeholder="Dla planów (np. starter,business)" className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                <input type="text" value={newAnnouncement.target_products} onChange={e => setNewAnnouncement(p => ({ ...p, target_products: e.target.value }))} placeholder="Dla produktów (np. shiftplanner)" className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                <select value={newAnnouncement.action_type} onChange={e => setNewAnnouncement(p => ({ ...p, action_type: e.target.value, requires_action: !!e.target.value }))} className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                  <option value="">Bez akcji (informacyjny)</option>
                  <option value="price_change">Zmiana ceny (akceptuj/anuluj)</option>
                  <option value="subscription_cancel">Info o subskrypcji</option>
                </select>
              </div>
              <div className="flex gap-3">
                <button onClick={async () => {
                  try {
                    const r = await fetch(`${API}/admin/announcements`, { method: 'POST', headers, body: JSON.stringify(newAnnouncement) });
                    if (!r.ok) throw new Error((await r.json()).error);
                    setNewAnnouncement({ title: '', message: '', type: 'info', target_plans: '', target_products: '', requires_action: false, action_type: '' });
                    fetchData();
                  } catch (err) { alert(err.message); }
                }} className="bg-primary text-white px-5 py-2 rounded-lg text-sm font-medium hover:bg-primary-dark cursor-pointer">Opublikuj</button>
                <button onClick={async () => {
                  try {
                    const r = await fetch(`${API}/admin/announcements`, { method: 'POST', headers, body: JSON.stringify({ ...newAnnouncement, sendEmail: true }) });
                    if (!r.ok) throw new Error((await r.json()).error);
                    setNewAnnouncement({ title: '', message: '', type: 'info', target_plans: '', target_products: '', requires_action: false, action_type: '' });
                    fetchData();
                    alert('Komunikat opublikowany + email wysłany!');
                  } catch (err) { alert(err.message); }
                }} className="bg-teal-600 text-white px-5 py-2 rounded-lg text-sm font-medium hover:bg-teal-700 cursor-pointer">Opublikuj + wyślij email</button>
              </div>
            </div>
            <div className="space-y-3">
              {announcements.map(a => (
                <div key={a.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 flex items-center justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                        a.type === 'warning' ? 'bg-yellow-500/20 text-yellow-400' :
                        a.type === 'danger' ? 'bg-red-500/20 text-red-400' :
                        a.type === 'success' ? 'bg-green-500/20 text-green-400' :
                        'bg-blue-500/20 text-blue-400'
                      }`}>{a.type}</span>
                      <span className={`px-2 py-0.5 rounded text-xs ${a.active ? 'bg-green-500/20 text-green-400' : 'bg-slate-600 text-slate-400'}`}>{a.active ? 'aktywny' : 'wyłączony'}</span>
                      {a.action_type && <span className="px-2 py-0.5 rounded text-xs bg-purple-500/20 text-purple-400">{a.action_type}</span>}
                    </div>
                    <p className="font-medium">{a.title}</p>
                    <p className="text-sm text-slate-400">{a.message}</p>
                  </div>
                  <div className="flex gap-2 ml-4 flex-shrink-0">
                    <button onClick={async () => {
                      await fetch(`${API}/admin/announcements/${a.id}/toggle`, { method: 'PUT', headers });
                      fetchData();
                    }} className="text-xs text-slate-400 hover:text-white cursor-pointer">{a.active ? 'Wyłącz' : 'Włącz'}</button>
                    <button onClick={async () => {
                      if (!confirm('Usunąć komunikat?')) return;
                      await fetch(`${API}/admin/announcements/${a.id}`, { method: 'DELETE', headers });
                      fetchData();
                    }} className="text-xs text-red-400 hover:text-red-300 cursor-pointer">Usuń</button>
                  </div>
                </div>
              ))}
              {announcements.length === 0 && <p className="text-slate-500 text-center py-8">Brak komunikatów</p>}
            </div>
          </div>
        )}

        {/* Mass email */}
        {tab === 'email' && (
          <div>
            <h2 className="text-xl font-bold mb-4">Wyślij email</h2>
            <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 space-y-4">
              {emailMsg && <div className="text-sm text-green-400 font-medium">{emailMsg}</div>}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input type="text" value={emailForm.subject} onChange={e => setEmailForm(p => ({ ...p, subject: e.target.value }))} placeholder="Temat emaila" className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary" />
                <select value={emailForm.targetPlan} onChange={e => setEmailForm(p => ({ ...p, targetPlan: e.target.value }))} className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none cursor-pointer">
                  <option value="">Wszyscy użytkownicy</option>
                  <option value="trial">Tylko trial</option>
                  <option value="starter">Plan Starter</option>
                  <option value="business">Plan Business</option>
                  <option value="enterprise">Plan Enterprise</option>
                </select>
              </div>
              <textarea value={emailForm.body} onChange={e => setEmailForm(p => ({ ...p, body: e.target.value }))} placeholder="Treść emaila (HTML dozwolony)" rows={8} className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-primary font-mono" />
              <div className="flex gap-3 items-center">
                <button onClick={async () => {
                  if (!emailForm.subject || !emailForm.body) return alert('Uzupełnij temat i treść');
                  if (!confirm(`Wyślij email do ${emailForm.targetPlan || 'wszystkich'}?`)) return;
                  try {
                    const r = await fetch(`${API}/admin/send-email`, { method: 'POST', headers, body: JSON.stringify(emailForm) });
                    const data = await r.json();
                    if (!r.ok) throw new Error(data.error);
                    setEmailMsg(`Email wysłany do ${data.sent || '?'} użytkowników!`);
                    setEmailForm({ subject: '', body: '', targetPlan: '' });
                    setTimeout(() => setEmailMsg(''), 5000);
                  } catch (err) { alert(err.message); }
                }} className="bg-primary text-white px-6 py-2.5 rounded-lg text-sm font-medium hover:bg-primary-dark cursor-pointer">📤 Wyślij email</button>
                <p className="text-xs text-slate-500">Email zostanie wysłany przez skonfigurowany SMTP.</p>
              </div>
            </div>
          </div>
        )}

        {/* 

        {/* Stats */}
        {tab === 'stats' && stats && (
          <div>
            <h2 className="text-xl font-bold mb-4">Statystyki</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
              {[
                { label: 'Firmy', value: stats.totalTenants, color: 'text-teal-400' },
                { label: 'Użytkownicy', value: stats.totalUsers, color: 'text-blue-400' },
                { label: 'Aktywne subskrypcje', value: stats.activeSubscriptions, color: 'text-green-400' },
                { label: 'W trialu', value: stats.trialTenants, color: 'text-yellow-400' },
              ].map((s, i) => (
                <div key={i} className="bg-slate-800 rounded-xl border border-slate-700 p-5">
                  <p className="text-xs text-slate-400 mb-1">{s.label}</p>
                  <p className={`text-3xl font-bold ${s.color}`}>{s.value}</p>
                </div>
              ))}
            </div>
            <div className="bg-slate-800 rounded-xl border border-slate-700 p-5">
              <h3 className="text-sm font-semibold text-slate-300 mb-3">Firmy wg planu</h3>
              <div className="space-y-2">
                {(stats.byPlan || []).map((bp, i) => (
                  <div key={i} className="flex items-center justify-between text-sm">
                    <span className="text-slate-400">{bp.plan}</span>
                    <span className="font-bold">{bp.count}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
